[package]
name = "assignment_2"
version = "0.1.0"
authors = ["MAK <aqib.khan.25@iiee.edu.pk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
